name: Native CI

on: push

jobs:

  verify:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - java11
        graalvm-version:
          - 20.0.0
          - 20.1.0

    steps:
      - uses: actions/checkout@v1
      - name: Setup GraalVM CE
        uses: rinx/setup-graalvm-ce@v0.0.1
        with:
          graalvm-version: ${{ matrix.graalvm-version }}
          java-version: ${{ matrix.java-version }}
      - name: setup-native-image
        run: gu install native-image
      - name: Info
        run: mvn -version
      - name: Start Database
        run: ./docker/start_db_single.sh docker.io/arangodb/arangodb:3.6.4
      - name: compile native
        run: mvn package -Pnative-image
      - name: start native server
        run: ./target/arango-helidon-native-example -Dserver.port=8081 &
      - name: test
        run: mvn test

